In [1]:
pip install kaggle

Collecting kaggle
  Downloading kaggle-1.8.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: black>=24.10.0 in c:\users\pmls\anaconda\lib\site-packages (from kaggle) (24.10.0)
Requirement already satisfied: bleach in c:\users\pmls\anaconda\lib\site-packages (from kaggle) (6.2.0)
Collecting kagglesdk (from kaggle)
  Downloading kagglesdk-0.1.13-py3-none-any.whl.metadata (13 kB)
Collecting mypy>=1.15.0 (from kaggle)
  Downloading mypy-1.19.1-cp313-cp313-win_amd64.whl.metadata (2.3 kB)
Requirement already satisfied: protobuf in c:\users\pmls\anaconda\lib\site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in c:\users\pmls\anaconda\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\pmls\anaconda\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\pmls\anaconda\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\pmls\anaconda\lib\site-packages (from kaggle) (72.1.0)
Requirement already satisfied: six>=1.10 in c:\users\pmls\anaconda\lib\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: tqdm in c:\users\pmls\anaconda\lib\site-packages (from kaggle) (4.67.1)
Collecting types-requests (from kaggle)
  Downloading types_requests-2.32.4.20250913-py3-none-any.whl.metadata (2.0 kB)
Collecting types-tqdm (from kaggle)
  Downloading types_tqdm-4.67.0.20250809-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\pmls\anaconda\lib\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: click>=8.0.0 in c:\users\pmls\anaconda\lib\site-packages (from black>=24.10.0->kaggle) (8.1.8)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\users\pmls\anaconda\lib\site-packages (from black>=24.10.0->kaggle) (1.0.0)
Requirement already satisfied: packaging>=22.0 in c:\users\pmls\anaconda\lib\site-packages (from black>=24.10.0->kaggle) (24.2)
Requirement already satisfied: pathspec>=0.9.0 in c:\users\pmls\anaconda\lib\site-packages (from black>=24.10.0->kaggle) (0.10.3)
Requirement already satisfied: platformdirs>=2 in c:\users\pmls\anaconda\lib\site-packages (from black>=24.10.0->kaggle) (4.3.7)
Requirement already satisfied: colorama in c:\users\pmls\anaconda\lib\site-packages (from click>=8.0.0->black>=24.10.0->kaggle) (0.4.6)
Requirement already satisfied: typing_extensions>=4.6.0 in c:\users\pmls\anaconda\lib\site-packages (from mypy>=1.15.0->kaggle) (4.15.0)
Collecting librt>=0.6.2 (from mypy>=1.15.0->kaggle)
  Downloading librt-0.7.4-cp313-cp313-win_amd64.whl.metadata (1.4 kB)
Requirement already satisfied: webencodings in c:\users\pmls\anaconda\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\pmls\anaconda\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\pmls\anaconda\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pmls\anaconda\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pmls\anaconda\lib\site-packages (from requests->kaggle) (2025.11.12)
Downloading kaggle-1.8.2-py3-none-any.whl (256 kB)
Downloading mypy-1.19.1-cp313-cp313-win_amd64.whl (10.1 MB)
   ---------------------------------------- 0.0/10.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/10.1 MB 5.2 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/10.1 MB 11.3 MB/s eta 0:00:01
   ---------------------------- ----------- 7.3/10.1 MB 13.5 MB/s eta 0:00:01
   ---------------------------------------- 10.1/10.1 MB 13.6 MB/s eta 0:00:00
Downloading librt-0.7.4-cp313-cp313-win_amd64.whl (49 kB)
Downloading kagglesdk-0.1.13-py3-none-any.whl (159 kB)
Downloading types_requests-2.32.4.20250913-py3-none-any.whl (20 kB)
Downloading types_tqdm-4.67.0.20250809-py3-none-any.whl (24 kB)
Installing collected packages: types-requests, librt, types-tqdm, mypy, kagglesdk, kaggle

  Attempting uninstall: mypy

    Found existing installation: mypy 1.14.1

   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
    Uninstalling mypy-1.14.1:
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
      Successfully uninstalled mypy-1.14.1
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------- ------------------- 3/6 [mypy]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   -------------------------- ------------- 4/6 [kagglesdk]
   --------------------------------- ------ 5/6 [kaggle]
   --------------------------------- ------ 5/6 [kaggle]
   --------------------------------- ------ 5/6 [kaggle]
   --------------------------------- ------ 5/6 [kaggle]
   --------------------------------- ------ 5/6 [kaggle]
   --------------------------------- ------ 5/6 [kaggle]
   --------------------------------- ------ 5/6 [kaggle]
   ---------------------------------------- 6/6 [kaggle]

Successfully installed kaggle-1.8.2 kagglesdk-0.1.13 librt-0.7.4 mypy-1.19.1 types-requests-2.32.4.20250913 types-tqdm-4.67.0.20250809
Note: you may need to restart the kernel to use updated packages.

In [7]:
!kaggle --version

Kaggle API 1.8.2

In [11]:
!kaggle datasets list

ref                                                              title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
---------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
wardabilal/spotify-global-music-dataset-20092025                 Spotify Global Music Dataset (2009–2025)               1289021  2025-11-11 09:43:05.933000          16387        395                1
neurocipher/heartdisease                                         Heart Disease                                             3491  2025-12-11 15:29:14.327000           2114         57                1
kundanbedmutha/exam-score-prediction-dataset                     Exam Score Prediction Dataset                           325454  2025-11-28 07:29:01.047000           5863        130                1
prince7489/laptop-battery-health-and-usage-dataset               Laptop Battery Health & Usage Dataset                     1063  2025-12-15 15:26:25.363000            842         23        0.9411765
neurocipher/student-performance                                  Student Performance                                      49705  2025-12-12 12:06:28.973000           1261         43                1
ajinkyachintawar/sales-and-customer-behaviour-insights           Sales & Customer Behaviour Insights                      57108  2025-12-13 09:22:09.340000           1086         35                1
aatifahmad123/weather-and-air-quality-of-indian-cities           Weather and Air Quality of Indian Cities                  3778  2025-12-14 12:17:28.007000            551         22                1
kundanbedmutha/student-performance-dataset                       Student Performance Dataset                             528850  2025-11-17 15:22:39.130000           2873         48                1
rohiteng/amazon-sales-dataset                                    Amazon Sales Dataset                                   4037578  2025-11-23 14:29:37.973000           6167         86                1
khushikyad001/ai-impact-on-jobs-2030                             AI Impact on Jobs 2030                                   87410  2025-11-09 17:58:05.410000           9274        202                1
ranaghulamnabi/shopping-behavior-and-preferences-study           Shopping Behavior & Preferences Study                    72157  2025-12-03 09:14:26.797000           2201         53                1
siddharth0935/toy-store-e-commerce-database                      Toy Store E-Commerce Database                         16395906  2025-12-15 06:07:31.377000            574         26                1
ziya07/drugpatient-dataset-for-ckd-prediction                    Drug–Patient Dataset for CKD Prediction                  98843  2025-12-13 08:39:29.293000            521         22       0.88235295
salmanabdu/tokopedia-product-reviews-2025                        Tokopedia Product Reviews 2025                         3707285  2025-12-11 21:47:03.400000            350         23                1
dhairyajeetsingh/ecommerce-customer-behavior-dataset             Ecommerce Customer Behavior Dataset                    2058138  2025-12-13 11:27:03.180000            177         29                1
miadul/credit-card-fraud-detection-dataset                       Credit Card Fraud Detection Dataset                     113829  2025-12-17 14:34:52.713000            369         23        0.7058824
mihikaajayjadhav/top-100-cryptocurrencies-daily-price-data-2025  Top 100 Cryptocurrencies - Daily Price Data (2025)     2702953  2025-12-04 05:57:33.417000            765         25                1
ankushnarwade/indian-climate-dataset-20242025                    Indian Climate Dataset (2024–2025)                      155173  2025-12-14 09:44:06.193000            884         23                1
umitka/twitter-toxic-tweets                                      Twitter Toxic Tweets                                   1291556  2025-12-14 12:42:41.337000            476         25                1
aliiihussain/spotify-analysis-and-visualization                  Spotify Analysis & Visualization                          2369  2025-12-02 19:08:42.523000           1344         33                1

In [13]:
import kaggle
Url = 'https://www.kaggle.com/datasets/ankitbansal06/retail-orders'
!kaggle datasets download -d ankitbansal06/retail-orders

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
retail-orders.zip: Skipping, found more recently modified local copy (use --force to force download)

In [20]:
import zipfile

with zipfile.ZipFile("retail-orders.zip", "r") as zip_ref:
    zip_ref.extractall("retail-orders")

print("Extraction completed")

Extraction completed

In [31]:
import pandas as pd
df = pd.read_csv('retail-orders/orders.csv',na_values = ['Not Available','unknown'])

df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [33]:
df['Ship Mode'].unique()
df.columns.str.upper()

Index(['ORDER ID', 'ORDER DATE', 'SHIP MODE', 'SEGMENT', 'COUNTRY', 'CITY',
       'STATE', 'POSTAL CODE', 'REGION', 'CATEGORY', 'SUB CATEGORY',
       'PRODUCT ID', 'COST PRICE', 'LIST PRICE', 'QUANTITY',
       'DISCOUNT PERCENT'],
      dtype='object')

In [34]:
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [35]:
df.columns=df.columns.str.replace(' ','-')

In [47]:
df.head()
df['Discount-Price']=df['List-Price']*df['Discount-Percent']*.01
df['Sell-Price'] = df['List-Price']-df['Discount-Price']
df['Sales']=df['Sell-Price']*df['Quantity']
df.head(20)

,Order-Id,Order-Date,Ship-Mode,Segment,Country,City,State,Postal-Code,Region,Category,Sub-Category,Product-Id,cost-price,List-Price,Quantity,Discount-Percent,Discount-Price,Sell-Price,revenue-per-order,Sales
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,509.6,509.6
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,2124.3,2124.3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,19.0,19.0
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,4704.0,4704.0
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,38.0,38.0
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3,1.5,48.5,339.5,339.5
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3,0.3,9.7,38.8,38.8
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5,45.5,864.5,5187.0,5187.0
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2,0.4,19.6,58.8,58.8
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3,3.3,106.7,533.5,533.5
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3,51.3,1658.7,14928.3,14928.3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3,27.3,882.7,3530.8,3530.8
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3,0.6,19.4,58.2,58.2
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2,8.2,401.8,1205.4,1205.4
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5,3.5,66.5,332.5,332.5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5,0.0,0.0,0.0,0.0
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3,20.1,649.9,3899.4,3899.4
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4,2.4,57.6,115.2,115.2
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4,0.4,9.6,19.2,19.2
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3,6.3,203.7,611.1,611.1

In [48]:
!pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in c:\users\pmls\anaconda\lib\site-packages (2.0.39)
Requirement already satisfied: pyodbc in c:\users\pmls\anaconda\lib\site-packages (5.2.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\pmls\anaconda\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pmls\anaconda\lib\site-packages (from sqlalchemy) (4.15.0)

In [50]:
from sqlalchemy import create_engine
engine = create_engine("mssql+pyodbc://DESKTOP-8BL3MIG\MSSQLSERVER1/RetailDB"
    "?driver=ODBC+Driver+17+for+SQL+Server")

In [51]:
df.to_sql(name='retail_orders',con = engine, if_exists='replace',index = False)

10